name: NodeJS with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack
      - run: |
          git config user.name "Build Script"
          git config user.email "<>"
          git fetch --all
      - run: |
          git switch release
          rm -r scripts/
          mkdir -p scripts/
          mv dist/boycotto.js scripts/boycotto.js
          mv mafia/dependencies.txt dependencies.txt
          git add dependencies.txt
          git add scripts/
          git commit -m "Build Mafia files for commit $GITHUB_SHA"
          git push origin release
      - run: |
          git switch release-data
          rm -r data/
          mkdir -p data/
          mv mafia/data/boycotto_stores.txt data/boycotto_stores.txt
          git add data/
          git commit -m "Build Data file for commit $GITHUB_SHA"
          git push origin release-data
